
##services:
##  zookeeper:
##    image: confluentinc/cp-zookeeper:7.3.2
##    environment:
##      ZOOKEEPER_CLIENT_PORT: 2181
##      ZOOKEEPER_TICK_TIME: 2000
##    ports:
##      - "2181:2181"

##  kafka:
##    image: confluentinc/cp-kafka:7.3.2
##    ports:
##      - "9092:9092"
##    environment:
##      KAFKA_BROKER_ID: 1
##      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
##      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://localhost:9092}
##      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
##      KAFKA_CREATE_TOPICS: "reddit_comments:1:1:retention.ms=600000,retention.bytes=10485760"
##    networks:
##      - reddit-sentiment
##networks:
##  reddit-sentiment:
##    driver: bridge

version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    mem_limit: 512m
    mem_reservation: 256m
    networks:
      - reddit-sentiment
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'ruok' | nc -w 2 zookeeper 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 3
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    mem_limit: 1g
    mem_reservation: 512m
    networks:
      - reddit-sentiment
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  reddit-sentiment:
    driver: bridge

