name: Run Kafka Stream Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0
  workflow_dispatch:     # Allow manual triggering
  push:               # Trigger on push events

jobs:
  run-kafka-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or whatever version you use

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Compose
        run: |
          docker compose up -d
          echo "Kafka + Zookeeper starting up..."
          sleep 30  # Give services time to initialize

      - name: Run Producer (Reddit Stream)
        run: |
          echo "Starting producer..."
          python producer/reddit_stream_producer.py

      - name: Run Consumer (Sentiment Consumer)
        run: |
          echo "Starting consumer..."
          timeout 120s python3 consumer/sentiment_consumer.py

      - name: Shut down Docker Compose
        run: docker-compose down
